name: Release Multi-Plateforme
on:
  push:
    tags:
      - 'v*' # Se déclenche quand tu crées un tag genre v1.0.2

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build & Publish
        run: npm install && npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}