name: Release Multi-Plateforme
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # TRÈS IMPORTANT : Si Linux plante, Windows et Mac finissent quand même
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # On passe à la version stable actuelle

      - name: Install dependencies
        run: npm install

      - name: Build & Publish
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}