name: Release

on:
  push:
    tags:
      - 'v*' # C'est ce "v*" qui surveille les tags créés par npm version

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        # Utiliser la version de développement qui supporte Node 24+
        uses: actions/checkout@v4.2.2 

      - name: Setup Node
        # Utiliser la version qui intègre déjà les correctifs pour Node 24
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}